name = "edge-concierge"
main = "./backend/worker.ts"
compatibility_date = "2025-08-01"

[ai]
binding = "AI"

[[vectorize]]
binding = "MEM_INDEX"
index_name = "edge-mem"

[[kv_namespaces]]
binding = "KV"
id = "4d0f0a5a3456479697c62ba5c986486b"

[vars]
LLM_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast"
EMB_MODEL = "@cf/baai/bge-base-en-v1.5"